import { Schema, model, type Types } from 'mongoose';
import type { BaseDoc } from './types';

/**
 * A supplier the shop sources stock from (Clothing POS).
 *
 * WORKSPACE-LEVEL, deliberately: a clothing business buys from the same
 * wholesalers for every branch, so a supplier belongs to the workspace and all
 * of its branches see the same list. Products, customers and categories are
 * branch-scoped because they are branch inventory and branch footfall; a
 * sourcing contact is neither. See docs/SUPPLIER_MANAGEMENT.md.
 *
 * Today this is a contact record. The shape is deliberately ready for the
 * purchase modules that will follow: a stable `_id` to reference, a stable
 * human code, a status that retires a supplier without destroying it, and NO
 * product relationship baked in (a product may be bought from several suppliers
 * over time, so that link belongs on the purchase record, not here).
 */
export const SUPPLIER_TYPES = ['manufacturer', 'wholesaler', 'distributor', 'importer', 'local', 'other'] as const;
export type SupplierType = (typeof SUPPLIER_TYPES)[number];

export const PAYMENT_TERMS = ['cash', 'on_delivery', 'net_7', 'net_15', 'net_30', 'net_60', 'other'] as const;
export type PaymentTerm = (typeof PAYMENT_TERMS)[number];

export interface SupplierAddress {
  line1: string;
  line2: string;
  area: string;
  city: string;
  district: string;
  division: string;
  postalCode: string;
  country: string;
}

export interface SupplierContact {
  name: string;
  designation: string;
  phone: string;
  altPhone: string;
  email: string;
}

/** Banking details. Never returned by the list API - see the service. */
export interface SupplierBanking {
  accountName: string;
  accountNumber: string;
  bankName: string;
  branchName: string;
}

export interface SupplierDoc extends BaseDoc {
  tenantId: Types.ObjectId;
  /** `SUP-0001`, unique per workspace, generated by the server. */
  code: string;
  name: string;
  type: SupplierType;
  contact: SupplierContact;
  phone: string;
  email: string;
  website: string;
  address: SupplierAddress;
  taxNumber: string;
  tradeLicense: string;
  banking: SupplierBanking;
  paymentTerms: PaymentTerm;
  paymentTermsNote: string;
  notes: string;
  isActive: boolean;
  deletedAt: Date | null;
  createdBy: Types.ObjectId | null;
  updatedBy: Types.ObjectId | null;
}

const addressSchema = new Schema<SupplierAddress>(
  {
    line1: { type: String, default: '', trim: true, maxlength: 200 },
    line2: { type: String, default: '', trim: true, maxlength: 200 },
    area: { type: String, default: '', trim: true, maxlength: 120 },
    city: { type: String, default: '', trim: true, maxlength: 120 },
    district: { type: String, default: '', trim: true, maxlength: 120 },
    division: { type: String, default: '', trim: true, maxlength: 120 },
    postalCode: { type: String, default: '', trim: true, maxlength: 16 },
    country: { type: String, default: '', trim: true, maxlength: 80 },
  },
  { _id: false },
);

const contactSchema = new Schema<SupplierContact>(
  {
    name: { type: String, default: '', trim: true, maxlength: 160 },
    designation: { type: String, default: '', trim: true, maxlength: 120 },
    phone: { type: String, default: '', trim: true, maxlength: 32 },
    altPhone: { type: String, default: '', trim: true, maxlength: 32 },
    email: { type: String, default: '', trim: true, lowercase: true, maxlength: 200 },
  },
  { _id: false },
);

const bankingSchema = new Schema<SupplierBanking>(
  {
    accountName: { type: String, default: '', trim: true, maxlength: 160 },
    accountNumber: { type: String, default: '', trim: true, maxlength: 64 },
    bankName: { type: String, default: '', trim: true, maxlength: 160 },
    branchName: { type: String, default: '', trim: true, maxlength: 160 },
  },
  { _id: false },
);

const supplierSchema = new Schema<SupplierDoc>(
  {
    tenantId: { type: Schema.Types.ObjectId, ref: 'Tenant', required: true, index: true },
    code: { type: String, required: true, trim: true, uppercase: true, maxlength: 32 },
    name: { type: String, required: true, trim: true, maxlength: 160 },
    type: { type: String, enum: SUPPLIER_TYPES, default: 'other' },
    contact: { type: contactSchema, default: () => ({}) },
    phone: { type: String, default: '', trim: true, maxlength: 32 },
    email: { type: String, default: '', trim: true, lowercase: true, maxlength: 200 },
    website: { type: String, default: '', trim: true, maxlength: 300 },
    address: { type: addressSchema, default: () => ({}) },
    taxNumber: { type: String, default: '', trim: true, maxlength: 64 },
    tradeLicense: { type: String, default: '', trim: true, maxlength: 64 },
    banking: { type: bankingSchema, default: () => ({}) },
    paymentTerms: { type: String, enum: PAYMENT_TERMS, default: 'cash' },
    paymentTermsNote: { type: String, default: '', trim: true, maxlength: 120 },
    notes: { type: String, default: '', maxlength: 2000 },
    isActive: { type: Boolean, default: true },
    deletedAt: { type: Date, default: null },
    createdBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
    updatedBy: { type: Schema.Types.ObjectId, ref: 'User', default: null },
  },
  { timestamps: true },
);

// One code per workspace. The partial filter frees a deleted supplier's code.
supplierSchema.index({ tenantId: 1, code: 1 }, { unique: true, partialFilterExpression: { deletedAt: null } });
// The list: a workspace's live suppliers, newest first or by name.
supplierSchema.index({ tenantId: 1, deletedAt: 1, isActive: 1, name: 1 });
supplierSchema.index({ tenantId: 1, deletedAt: 1, createdAt: -1 });
// Search by name, code, contact person, phone or email.
supplierSchema.index({ tenantId: 1, name: 1 });
supplierSchema.index({ tenantId: 1, phone: 1 });
supplierSchema.index({ tenantId: 1, email: 1 });
supplierSchema.index({ tenantId: 1, 'contact.name': 1 });
supplierSchema.index({ tenantId: 1, 'contact.phone': 1 });

export const SupplierModel = model<SupplierDoc>('Supplier', supplierSchema);
