import { z } from 'zod';
import { PAYMENT_PROVIDERS } from '../../config/constants';
import { CATALOG_PLAN_CODE_PATTERN } from '../../models/CatalogPlan';
import { BILLING_CYCLES } from '../../models/PlanPrice';
import { httpUrl } from '../common/common.validators';

/**
 * Buying a plan is described in catalog terms only: which plan, which billing
 * cycle, how to pay. The POS type is the workspace's own. There is no field for
 * an amount, a price, a discount or a wallet deduction, and `.strict()` refuses
 * one if it is sent - the server prices every purchase itself.
 */
const plan = z.string().trim().regex(CATALOG_PLAN_CODE_PATTERN, 'Unknown plan');
const billingCycle = z.enum(BILLING_CYCLES);
const couponCode = z.string().trim().min(1).max(32).optional();
const note = z.string().trim().max(500).optional().default('');
/** Generated by the client per purchase attempt; a retry with the same key returns the first result. */
const idempotencyKey = z
  .string()
  .trim()
  .regex(/^[A-Za-z0-9_-]{8,100}$/, 'Use 8-100 letters, digits, _ or -')
  .optional();

export const purchaseQuoteSchema = z.object({ plan, billingCycle, couponCode }).strict();

export const purchaseSchema = z.discriminatedUnion('paymentMethod', [
  z.object({ paymentMethod: z.literal('wallet'), plan, billingCycle, couponCode, note, idempotencyKey }).strict(),
  z
    .object({
      paymentMethod: z.literal('online'),
      plan,
      billingCycle,
      provider: z.enum([PAYMENT_PROVIDERS.BKASH]),
      returnUrl: httpUrl.optional(),
      cancelUrl: httpUrl.optional(),
      couponCode,
      idempotencyKey,
    })
    .strict(),
  z
    .object({
      paymentMethod: z.literal('manual'),
      plan,
      billingCycle,
      manualMethod: z.enum([PAYMENT_PROVIDERS.BKASH, PAYMENT_PROVIDERS.NAGAD, PAYMENT_PROVIDERS.BANK]),
      senderNumber: z.string().trim().min(6, 'Enter the number you paid from').max(32),
      transactionId: z.string().trim().min(4, 'Enter the transaction ID').max(64),
      couponCode,
      note,
      idempotencyKey,
    })
    .strict(),
]);

export const autoRenewSchema = z.object({ enabled: z.boolean() }).strict();

/** The plan to renew into at the end of the period. Catalog terms only, like a purchase. */
export const scheduleChangeSchema = z.object({ plan, billingCycle }).strict();

export type ScheduleChangeInput = z.infer<typeof scheduleChangeSchema>;
export type PurchaseQuoteInput = z.infer<typeof purchaseQuoteSchema>;
export type PurchaseInput = z.infer<typeof purchaseSchema>;

/**
 * Checkout for an owned workspace: exactly a purchase, plus (optionally) the
 * payable amount the customer was shown. It is never charged - the server
 * prices the purchase again - it only lets the server refuse when the price
 * changed between the quote and the confirmation.
 */
const expectedPayable = { expectedPayableMinor: z.number().int().min(0).max(1_000_000_000).optional() };
export const workspaceCheckoutSchema = z.discriminatedUnion('paymentMethod', [
  purchaseSchema.options[0].extend(expectedPayable),
  purchaseSchema.options[1].extend(expectedPayable),
  purchaseSchema.options[2].extend(expectedPayable),
]);
export type WorkspaceCheckoutInput = z.infer<typeof workspaceCheckoutSchema>;
